# Generated by Django 4.2.3 on 2023-07-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_ordertransaction_money_tender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='money_tender',
            field=models.FloatField(),
        ),
    ]
