# Generated by Django 4.2.3 on 2023-07-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_ordertransaction_money_tender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertransaction',
            name='money_tender',
        ),
    ]
