# Generated by Django 4.2.3 on 2023-07-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_ordertransaction_money_tender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_by', models.CharField(max_length=120)),
                ('item_name', models.CharField(max_length=120)),
                ('message', models.CharField(blank=True, max_length=120, null=True)),
                ('is_noted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
