# Generated by Django 4.2.3 on 2023-07-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_customer_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='product',
            name='on_display',
            field=models.BooleanField(default=True),
        ),
    ]
