# Generated by Django 4.2.3 on 2023-07-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_customer_options_product_on_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_display',
            field=models.BooleanField(default=True, verbose_name='this product is available?'),
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.timestampedmodel')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ordertransaction')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=('store.timestampedmodel',),
        ),
    ]
